### PR TITLE
feat(voxel_connectivity_graph): extracts directed voxel connectivity …

### PR DESCRIPTION
**Pull request by william-silversmith**
…graph

Each voxel of the output is a bitfield that represents the allowed
transit directions.

The situation this function is designed for is identifying "self touches" of neurons from a more detailed labeling and then applying algorithms to a higher-level labeling that might have no separation between adjacent labels that shouldn't be connected.

```
// Note that for 2D connectivities, this bitfield requires only 8-bits.

//      8      7      6      5      4      3      2      1
// ------ ------ ------ ------ ------ ------ ------ ------
//   -x-y    x-y    -xy     xy     -x     +y     -x     +x

// For a 3D 26 connectivity, we need to use a 32-bit integer.
// 6x unused, 8 corners, 12 edges, 6 faces

//     32     31     30     29     28     27     26     25     24     23     
// ------ ------ ------ ------ ------ ------ ------ ------ ------ ------
// unused unused unused unused unused unused -x-y-z  x-y-z -x+y-z +x+y-z
//
//     22     21     20     19     18     17     16     15     14     13
// ------ ------ ------ ------ ------ ------ ------ ------ ------ ------
// -x-y+z +x-y+z -x+y+z    xyz   -y-z    y-z   -x-z    x-z    -yz     yz
//
//     12     11     10      9      8      7      6      5      4      3
// ------ ------ ------ ------ ------ ------ ------ ------ ------ ------
//    -xz     xz   -x-y    x-y    -xy     xy     -z     +z     -y     +y  
//      2      1
// ------ ------
//     -x     +x
//
// 6 connected uses bits 1-6, 18 connected uses 1-18, 26 connected uses 1-26
```

### CODE REVIEW

**Comment by xiuluo211314** [comment]
@william-silversmith hello, you did a great job!  I am using this pro in my work. Can you explain the "transit directions" ？ like '-x-y'、‘-xy’...  And I also want to know how to get all voxel by graph. THX!

**Comment by william-silversmith** [comment]
Hi Xiuluo,

-x means moving left one space, -y means moving up one space, x means right one space, and y means down one space

Since the array is forced into Fortran order, -x means -1, +x means +1, -y means -size x, +y means +size x

I'm not sure what you mean by get all voxels by graph? The bitfields are returned as an image and you can scan it to find what you need?

**Comment by xiuluo211314** [comment]
Thank you for your answer！
In fact, I am doing some 3d modeling work and need to create mesh from graph structure. Can you provide some methods of graph conversion mesh？

**Comment by william-silversmith** [comment]
Can you explain a bit more what you are trying to do? Is there a reason you can't directly use the voxels to create the mesh? If you could, check out https://github.com/seung-lab/zmesh which can process a multi-valued volume.

**Pull request merged**
